salesforce:
  username: "siddhartha.pal@nttdata.com.sachin"
  password: "![ItAaX7qTsEywysnn8T89eQ==]"
  token: "![VaF4aS6gYQeAwFtFlIkTb+xzP8DRx8oNePxa6wSHz7M=]"
  url: "https://principalwine--sachin.sandbox.my.salesforce.com/services/Soap/u/58.0"
  account-event: "/data/AccountChangeEvent"
  contact-event: "/data/ContactChangeEvent"
  
sfdc:
  basepath: "/api/v1"
  host: "pw-sf-sys-api-dev-o4o3m1.5sc6y6-2.usa-e2.cloudhub.io"
  port: ""
  client-id: "![dSnqtH73b+K9XWFeVWquErgXi9NQsw1cBCJsHBG+sf9d1/QugFivAQ==]"
  client-secret: "![KcmRb2Ji/e7M+J0aZHTssR59lPrjftCgPfgNeAxP3aQ80HuYTwF5mg==]"
  upsert: "/upsert"
  query: "/query"