#%RAML 1.0 DataType 
type: object
properties:
  SaleID:
    type: string
    required: false
  TaskTypeSign:
    type: string | nil
    required: false
  IsServiceOnly:
    type: string | nil
    required: false
  SaleOrderNumber:
    type: string | nil
    required: false
  TaskID:
    type: string | nil
    required: false
  CustomerName:
    type: string | nil
    required: false
  CustomerContactName:
    type: string | nil
    required: false
  CustomerContactEmail:
    type: string | nil
    required: false
  SaleRepEmail:
    type: string | nil
    required: false
  DownloadLink:
    type: string | nil
    required: false
  EventType:
    type: string | nil
    required: false
